image: ruby:3.0.2

before_script:
  - bundle install
  - bin/rails tailwindcss:watch

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main
